name: Deploy Task Manager Backend

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker-compose build

      - name: Publish Image to docker hub
        run: docker push lincoln1000/task-manager-backend:latest
  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull and Deploy with Docker Compose
        env:
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
        run: |
          docker-compose down
          docker-compose pull
          docker-compose up -d
